## Travis CI Integration

language: c

install:
  - sudo add-apt-repository ppa:directhex/monoxide && sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild Stateflow.sln
